variable "name" {
  type        = "string"
  description = "The name of the API key"
}

variable "description" {
  type        = "string"
  description = "The API key description"
  default     = ""
}

variable "enabled" {
  type        = "string"
  description = "Specifies whether the API key can be used by callers (true or false) . Defaults to true"
  default     = "treu"
}

variable "value" {
  type        = "string"
  description = "The value of the API key. If not specified, it will be automatically generated by AWS on creation."
}
